name: Deploy React App to GitHub Pages
on:
  push:
    branches:
      - main  # Adjust to your default branch (e.g., master)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug GitHub Secrets
        run: |
          echo "Checking GitHub Secrets:"
          if [ -z "${{ secrets.REACT_APP_PROJECTID }}" ]; then
            echo "ERROR: REACT_APP_PROJECTID secret is not set!"
            exit 1
          else
            echo "REACT_APP_PROJECTID secret is set (value: ${{ secrets.REACT_APP_PROJECTID }})"
          fi
          if [ -z "${{ secrets.REACT_APP_APIKEY }}" ]; then
            echo "ERROR: REACT_APP_APIKEY secret is not set!"
            exit 1
          else
            echo "REACT_APP_APIKEY secret is set (value not shown for security)"
          fi
          if [ -z "${{ secrets.REACT_APP_DOMAIN }}" ]; then
            echo "ERROR: REACT_APP_DOMAIN secret is not set!"
            exit 1
          else
            echo "REACT_APP_DOMAIN secret is set (value: ${{ secrets.REACT_APP_DOMAIN }})"
          fi
          if [ -z "${{ secrets.REACT_APP_STORAGEBUCKET }}" ]; then
            echo "ERROR: REACT_APP_STORAGEBUCKET secret is not set!"
            exit 1
          else
            echo "REACT_APP_STORAGEBUCKET secret is set (value: ${{ secrets.REACT_APP_STORAGEBUCKET }})"
          fi
          if [ -z "${{ secrets.REACT_APP_MESSAGINGSENDERID }}" ]; then
            echo "ERROR: REACT_APP_MESSAGINGSENDERID secret is not set!"
            exit 1
          else
            echo "REACT_APP_MESSAGINGSENDERID secret is set (value: ${{ secrets.REACT_APP_MESSAGINGSENDERID }})"
          fi
          if [ -z "${{ secrets.REACT_APP_APPID }}" ]; then
            echo "ERROR: REACT_APP_APPID secret is not set!"
            exit 1
          else
            echo "REACT_APP_APPID secret is set (value: ${{ secrets.REACT_APP_APPID }})"
          fi
          if [ -z "${{ secrets.REACT_APP_MEASURMENTID }}" ]; then
            echo "ERROR: REACT_APP_MEASURMENTID secret is not set!"
            exit 1
          else
            echo "REACT_APP_MEASURMENTID secret is set (value: ${{ secrets.REACT_APP_MEASURMENTID }})"
          fi

      - name: Debug Environment Variables
        run: |
          echo "Listing REACT_APP_ environment variables:"
          env | grep REACT_APP_ | sort
          if [ -z "$REACT_APP_PROJECTID" ]; then
            echo "ERROR: REACT_APP_PROJECTID environment variable is not set!"
            exit 1
          else
            echo "REACT_APP_PROJECTID environment variable is set to: $REACT_APP_PROJECTID"
          fi

      - name: Build React App
        run: npm run build
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
          REACT_APP_DOMAIN: ${{ secrets.REACT_APP_DOMAIN }}
          REACT_APP_PROJECTID: ${{ secrets.REACT_APP_PROJECTID }}
          REACT_APP_STORAGEBUCKET: ${{ secrets.REACT_APP_STORAGEBUCKET }}
          REACT_APP_MESSAGINGSENDERID: ${{ secrets.REACT_APP_MESSAGINGSENDERID }}
          REACT_APP_APPID: ${{ secrets.REACT_APP_APPID }}
          REACT_APP_MEASURMENTID: ${{ secrets.REACT_APP_MEASURMENTID }}
          CI: false

      - name: Debug Build Output
        run: |
          echo "Checking for REACT_APP_PROJECTID in build files:"
          if [ -d "build/static/js" ]; then
            grep -r "REACT_APP_PROJECTID" build/static/js || echo "No REACT_APP_PROJECTID found in build files"
          else
            echo "ERROR: build/static/js directory not found!"
            exit 1
          fi
          echo "Listing build directory contents:"
          ls -R build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build

      - name: Debug Deployment
        run: |
          echo "Deployment to gh-pages completed. Checking gh-pages branch:"
          git ls-remote --heads origin gh-pages
